# embed-cert.ps1 - Reads the generated root CA certificate (DER) and writes
#                  src/UnderVolterCert.h as a C byte array.
#
# Called automatically by sign.ps1 and build.ps1.
# Run manually: .\Signer\embed-cert.ps1
#
# Output: src/UnderVolterCert.h  (UV_CERT_DER_SIZE = 0 when no cert found)

[CmdletBinding()]
param(
    [string]$CertDir,
    [string]$OutputHeader
)

Set-StrictMode -Version 3.0
$ErrorActionPreference = "Stop"

$ScriptDir = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }
if (-not $CertDir)      { $CertDir      = Join-Path $ScriptDir "cert" }
if (-not $OutputHeader) { $OutputHeader = Join-Path $ScriptDir "..\src\UnderVolterCert.h" }

$OutputHeader = [System.IO.Path]::GetFullPath($OutputHeader)

function Write-Stub {
    $lines = @(
        "// UnderVolterCert.h - Auto-generated by Signer/embed-cert.ps1",
        "// DO NOT EDIT. Run: .\\Signer\\sign.ps1 -Create  then  .\\build.ps1",
        "//",
        "// No certificate found - SelfEnroll is disabled.",
        "// Run .\\Signer\\sign.ps1 -Create to generate the root CA certificate.",
        "#pragma once",
        "",
        "static CONST UINT8  gUVCertDer[]  = { 0x00 };  // placeholder",
        "#define UV_CERT_DER_SIZE  ((UINTN)0)            // 0 = no cert embedded"
    )
    Set-Content -LiteralPath $OutputHeader -Value $lines -Encoding ASCII
    Write-Host "  embed-cert: no certificate found - stub written." -ForegroundColor Yellow
}

# Find root CA cert - named *-standard-root.cer by sign.ps1
$rootCer = Get-ChildItem -LiteralPath $CertDir -Filter "*-standard-root.cer" -ErrorAction SilentlyContinue |
           Sort-Object Name | Select-Object -First 1

if (-not $rootCer) {
    Write-Stub
    exit 0
}

try {
    $bytes = [System.IO.File]::ReadAllBytes($rootCer.FullName)
    if ($bytes.Length -eq 0) {
        Write-Stub
        exit 0
    }

    # Format as C hex array, 16 bytes per line
    $hexParts = @()
    for ($i = 0; $i -lt $bytes.Length; $i += 16) {
        $chunk = $bytes[$i .. [Math]::Min($i + 15, $bytes.Length - 1)]
        $hexParts += "    " + (($chunk | ForEach-Object { "0x{0:X2}" -f $_ }) -join ", ")
    }
    $hexBody = $hexParts -join ",`n"

    $lines = @(
        "// UnderVolterCert.h - Auto-generated by Signer/embed-cert.ps1",
        "// DO NOT EDIT. Regenerate with: .\\Signer\\sign.ps1 -Create  then  .\\build.ps1",
        "//",
        "// Root CA certificate (DER/binary X.509) enrolled by SelfEnroll into db, KEK, PK.",
        "// Any UnderVolter.efi signed with the corresponding leaf signing certificate",
        "// will be trusted by UEFI firmware after SelfEnroll completes.",
        "//",
        "// Certificate: $($rootCer.Name)  ($($bytes.Length) bytes)",
        "#pragma once",
        "",
        "static CONST UINT8 gUVCertDer[] = {",
        $hexBody,
        "};",
        "",
        "#define UV_CERT_DER_SIZE  ((UINTN)sizeof(gUVCertDer))"
    )

    Set-Content -LiteralPath $OutputHeader -Value $lines -Encoding ASCII
    Write-Host "  embed-cert: $($bytes.Length) bytes from $($rootCer.Name) -> UnderVolterCert.h" -ForegroundColor Green
}
catch {
    Write-Host "  embed-cert: ERROR - $($_.Exception.Message)" -ForegroundColor Red
    Write-Stub
}
